name = "ofenbau-innung-theme"
license = "MIT"
licenselink = "https://github.com/friedow/ofenbau-innung.de/blob/main/LICENSE"
description = "Theme of the ofenbau-innung.de website"
homepage = "https://github.com/friedow/ofenbau-innung.de"
demosite = "ofenbau-innung.de"
tags = []
features = []
min_version = "v0.1.0"
authors = [{ name = "Christian Friedow", homepage = "https://friedow.com" }]
